# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildconfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dotnet build --configuration $(buildconfiguration)
  displayName: 'Run a multi-line script'
